#!/usr/bin/env bash

export npm_config_disturl=https://atom.io/download/atom-shell
export npm_config_target=0.22.3
HOME=~/.atom-shell-gyp npm update --save
unset npm_config_disturl
unset npm_config_target
